#通信规则
dubbo:
  application:
    name: manage-web
  protocol:
    name: dubbo
    port: -1
  ## Dubbo Registry
  #dubbo.registry.address=N/A
  #注册中心 协议 和地址
  registry:
    address: zookeeper://192.168.0.3:2181
  scan:
    base-packages: com.aryun.gmall
server:
  port: 8083
    #添加日志级别
logging:
  level:
    root: info
#    com.aryun.gmall.user.mapper: trace
  pattern:
    conole: '%p%m%n'